version: "3"
services:
  server:
   build: server/
   command: python3 ./server.py
   ports:
     - 9999:9999
  client:
   build: client/   
   command: python3 ./client.py
   ports:
     - 9999:9999   
   depends_on:
     - server