version: "3"
services:
  server:
   network_mode: host
   build: server/
   command: python3 ./server.py
  client:
   build: client/   
   command: python3 ./client.py
   network_mode: host
   depends_on:
     - server
